name: NickUI
main: fernanACM\NickUI\Loader
version: 1.2.0
api: 4.0.0
author: fernanACM
description: A simple nickname user interface that is easy to customize by fernanACM
website: https://github.com/fernanACM

permissions:
  nickui.acm:
    default: op
    description: /nick - Open menu
  nickui.random:
    default: op
    description: /nick random - Command
