name: NickUI
main: fernanACM\NickUI\NickUI
version: 2.0.0
api: 5.3.0
author: fernanACM
description: A simple nickname user interface that is easy to customize by fernanACM
website: https://github.com/fernanACM

permissions:
  nickui.acm:
    default: op
    description: /nick - Open menu
  nickui.random:
    default: op
    description: /nick random - Command
